use bitflags::bitflags;
use serde::{Deserialize, Serialize};

/// Roots - fundamental execution targets acting as immutable substrates.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", content = "value")]
pub enum RootEntity {
    MemoryPointer(usize),
    DatabaseTable(String),
    NetworkSocket(u16),
    StateObject(String), // Abstract business entity
}

bitflags! {
    /// O(1) State Machine flags for deterministic token compilation.
    /// Replaces the O(n) Array traversal of suffix histories.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct StateFlags: u32 {
        const IS_ALLOCATED = 1 << 0;
        const IS_MUTABLE   = 1 << 1;
        const IS_SIGNED    = 1 << 2;
        const IS_STREAMING = 1 << 3;
    }
}

/// Suffixes - strictly isolated functions with a single zone of responsibility.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Hash)]
pub enum SuffixMorpheme {
    // Memory & State Management
    AllocHeap,
    MakeMutable,

    // I/O & Actions
    WriteToTarget,
    StreamData,

    // Cryptography & Protocols (PQC Ready)
    SignWithMLDSA(String), // The explicit Key Alias avoids Hidden Context
    VerifyConsensus,

    // Control Flow (Temporal markers)
    IterateUntilEmpty,
}

impl SuffixMorpheme {
    /// Returns the bitwise state transformation generated by this morpheme.
    pub fn as_flag(&self) -> StateFlags {
        match self {
            SuffixMorpheme::AllocHeap => StateFlags::IS_ALLOCATED,
            SuffixMorpheme::MakeMutable => StateFlags::IS_MUTABLE,
            SuffixMorpheme::SignWithMLDSA(_) => StateFlags::IS_SIGNED,
            SuffixMorpheme::StreamData => StateFlags::IS_STREAMING,
            _ => StateFlags::empty(),
        }
    }
}

/// The core registry emulating the Compatibility Matrix of the Kazak algorithm.
/// Defines strict topological rules for suffix agglutination in absolute O(1) time.
pub struct MorphemeRegistry;

impl MorphemeRegistry {
    /// Validates if a suffix can be logically applied to the current bitwise state of a root.
    /// O(1) time complexity guaranteed for 100k+ TPS core requirements.
    pub fn is_compatible(
        root: &RootEntity,
        current_state: StateFlags,
        new_suffix: &SuffixMorpheme,
    ) -> bool {
        match new_suffix {
            SuffixMorpheme::WriteToTarget => {
                // To write to memory or state, it must have been allocated or made mutable first
                match root {
                    RootEntity::DatabaseTable(_) | RootEntity::NetworkSocket(_) => true,
                    RootEntity::MemoryPointer(_) | RootEntity::StateObject(_) => {
                        current_state.intersects(StateFlags::IS_MUTABLE | StateFlags::IS_ALLOCATED)
                    }
                }
            }
            SuffixMorpheme::MakeMutable => {
                // A state cannot be made mutable twice in a row natively
                !current_state.contains(StateFlags::IS_MUTABLE)
            }
            SuffixMorpheme::SignWithMLDSA(_) => {
                // Cryptographic signatures are primarily applied to abstract State Objects or Mem Pointers
                matches!(
                    root,
                    RootEntity::StateObject(_) | RootEntity::MemoryPointer(_)
                )
            }
            SuffixMorpheme::StreamData => {
                // Streaming is typically bounded to Network Sockets
                matches!(root, RootEntity::NetworkSocket(_))
            }
            // By default, other morphemes have unconstrained agglutination in this MVP scope
            _ => true,
        }
    }
}
